<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260317133031 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE board_list (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(128) NOT NULL, position INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, project_id_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9E5EA13B6C1197C9 ON board_list (project_id_id)');
        $this->addSql('CREATE TABLE project (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(128) NOT NULL, description TEXT DEFAULT NULL, due TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, priority VARCHAR(255) DEFAULT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE project_member (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, role VARCHAR(128) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id_id INT NOT NULL, project_id_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_674011329D86650F ON project_member (user_id_id)');
        $this->addSql('CREATE INDEX IDX_674011326C1197C9 ON project_member (project_id_id)');
        $this->addSql('CREATE TABLE task (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(128) NOT NULL, description TEXT DEFAULT NULL, position INT NOT NULL, is_active BOOLEAN NOT NULL, due TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, project_id_id INT NOT NULL, board_list_id_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_527EDB256C1197C9 ON task (project_id_id)');
        $this->addSql('CREATE INDEX IDX_527EDB25AD9DEE8 ON task (board_list_id_id)');
        $this->addSql('CREATE TABLE task_assignment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, assigned_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, task_id_id INT NOT NULL, user_id_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2CD60F15B8E08577 ON task_assignment (task_id_id)');
        $this->addSql('CREATE INDEX IDX_2CD60F159D86650F ON task_assignment (user_id_id)');
        $this->addSql('CREATE TABLE task_comment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, content TEXT NOT NULL, task_id_id INT NOT NULL, user_id_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8B957886B8E08577 ON task_comment (task_id_id)');
        $this->addSql('CREATE INDEX IDX_8B9578869D86650F ON task_comment (user_id_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, firstname VARCHAR(50) NOT NULL, lastname VARCHAR(50) NOT NULL, email VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, job VARCHAR(128) DEFAULT NULL, roles JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE board_list ADD CONSTRAINT FK_9E5EA13B6C1197C9 FOREIGN KEY (project_id_id) REFERENCES project (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE project_member ADD CONSTRAINT FK_674011329D86650F FOREIGN KEY (user_id_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE project_member ADD CONSTRAINT FK_674011326C1197C9 FOREIGN KEY (project_id_id) REFERENCES project (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE task ADD CONSTRAINT FK_527EDB256C1197C9 FOREIGN KEY (project_id_id) REFERENCES project (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE task ADD CONSTRAINT FK_527EDB25AD9DEE8 FOREIGN KEY (board_list_id_id) REFERENCES board_list (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE task_assignment ADD CONSTRAINT FK_2CD60F15B8E08577 FOREIGN KEY (task_id_id) REFERENCES task (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE task_assignment ADD CONSTRAINT FK_2CD60F159D86650F FOREIGN KEY (user_id_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE task_comment ADD CONSTRAINT FK_8B957886B8E08577 FOREIGN KEY (task_id_id) REFERENCES task (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE task_comment ADD CONSTRAINT FK_8B9578869D86650F FOREIGN KEY (user_id_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE board_list DROP CONSTRAINT FK_9E5EA13B6C1197C9');
        $this->addSql('ALTER TABLE project_member DROP CONSTRAINT FK_674011329D86650F');
        $this->addSql('ALTER TABLE project_member DROP CONSTRAINT FK_674011326C1197C9');
        $this->addSql('ALTER TABLE task DROP CONSTRAINT FK_527EDB256C1197C9');
        $this->addSql('ALTER TABLE task DROP CONSTRAINT FK_527EDB25AD9DEE8');
        $this->addSql('ALTER TABLE task_assignment DROP CONSTRAINT FK_2CD60F15B8E08577');
        $this->addSql('ALTER TABLE task_assignment DROP CONSTRAINT FK_2CD60F159D86650F');
        $this->addSql('ALTER TABLE task_comment DROP CONSTRAINT FK_8B957886B8E08577');
        $this->addSql('ALTER TABLE task_comment DROP CONSTRAINT FK_8B9578869D86650F');
        $this->addSql('DROP TABLE board_list');
        $this->addSql('DROP TABLE project');
        $this->addSql('DROP TABLE project_member');
        $this->addSql('DROP TABLE task');
        $this->addSql('DROP TABLE task_assignment');
        $this->addSql('DROP TABLE task_comment');
        $this->addSql('DROP TABLE "user"');
    }
}
